[database]
driver = sql
username = postgres
database = loquillo_dev
# host = localhost
# port = 5432
# password =

# test_database = loquillo_test

# Memory drive for testing purposes
# driver = memory
