"""create_accounts_table

Revision ID: 0e7238102135
Revises: e91095ce02de
Create Date: 2022-09-24 19:54:55.764354

"""
from alembic import op
import sqlalchemy as sa


import database

# revision identifiers, used by Alembic.
revision = '0e7238102135'
down_revision = 'e91095ce02de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
        sa.Column('id', database.types.guid.GUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('name', sa.String(length=256), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.add_column('wallets', sa.Column('account_id', database.types.guid.GUID(), nullable=False))
    op.create_foreign_key(None, 'wallets', 'accounts', ['account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wallets', type_='foreignkey')
    op.drop_column('wallets', 'account_id')
    op.drop_table('accounts')
    # ### end Alembic commands ###
