"""delete events table

Revision ID: 7be0a3013364
Revises: 50befc10851d
Create Date: 2026-09-26 21:20:51.366399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import TIMESTAMP

# revision identifiers, used by Alembic.
revision: str = '7be0a3013364'
down_revision: Union[str, Sequence[str], None] = '50befc10851d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'events',
        sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('type', sa.VARCHAR(length=50), nullable=False),
        sa.Column('date', TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.Column('metadata', sa.TEXT(), nullable=False),
        sa.Column('created_at', TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('events_pkey'))
    )
    # ### end Alembic commands ###
