"""update transactions table

Revision ID: 814355a4162e
Revises: 7be0a3013364
Create Date: 2026-09-27 15:20:45.471705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '814355a4162e'
down_revision: Union[str, Sequence[str], None] = '7be0a3013364'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'description')
    op.add_column('transactions', sa.Column('note', sa.String(length=250), nullable=True))
    op.add_column(
        'transactions',
        sa.Column('date', sa.DateTime(), server_default=sa.text('now()'), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'transactions',
        sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=False)
    )
    op.drop_column('transactions', 'note')
    op.drop_column('transactions', 'date')
    # ### end Alembic commands ###
