"""create_categories_table

Revision ID: 9f8634d0a6e5
Revises: fcfcd49b63b7
Create Date: 2022-08-21 22:13:11.332607

"""
from alembic import op
import sqlalchemy as sa


import database

# revision identifiers, used by Alembic.
revision = '9f8634d0a6e5'
down_revision = 'fcfcd49b63b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
        sa.Column('id', database.types.guid.GUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('name', sa.String(length=256), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallets_categories',
        sa.Column('wallet_id', database.types.guid.GUID(), nullable=False),
        sa.Column('category_id', database.types.guid.GUID(), nullable=False),
        sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
        sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
        sa.PrimaryKeyConstraint('wallet_id', 'category_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallets_categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
