"""create loquillo wallets table

Revision ID: de1c9b2a11ff
Revises: 89b1fea4d4c0
Create Date: 2026-08-20 21:31:02.119667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de1c9b2a11ff'
down_revision: Union[str, Sequence[str], None] = '89b1fea4d4c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'loquillo_wallets',
        sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('incomes_account_id', sa.UUID(), nullable=False),
        sa.Column('expenses_account_id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(['expenses_account_id'], ['accounts.id'], ),
        sa.ForeignKeyConstraint(['incomes_account_id'], ['accounts.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loquillo_wallets')
    # ### end Alembic commands ###
