"""create_categories_table

Revision ID: debcee9894e2
Revises: 0e7238102135
Create Date: 2022-09-24 23:49:00.603939

"""
from alembic import op
import sqlalchemy as sa


import database

# revision identifiers, used by Alembic.
revision = 'debcee9894e2'
down_revision = '0e7238102135'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
        sa.Column('id', database.types.guid.GUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('name', sa.String(length=256), nullable=False),
        sa.Column('parent_category_id', database.types.guid.GUID(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['parent_category_id'], ['categories.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallets_categories',
        sa.Column('id', database.types.guid.GUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('account_id', database.types.guid.GUID(), nullable=False),
        sa.Column('category_id', database.types.guid.GUID(), nullable=False),
        sa.Column('wallet_id', database.types.guid.GUID(), nullable=False),
        sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
        sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
        sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallets_categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
