"""create_accounts_table

Revision ID: fcfcd49b63b7
Revises: e91095ce02de
Create Date: 2022-08-21 22:05:37.946375

"""
from alembic import op
import sqlalchemy as sa


import database

# revision identifiers, used by Alembic.
revision = 'fcfcd49b63b7'
down_revision = 'e91095ce02de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'accounts',
        sa.Column(
            'id', database.types.guid.GUID(),
            server_default=sa.text('gen_random_uuid()'),
            nullable=False
        ),
        sa.Column('name', sa.String(length=256), nullable=False),
        sa.Column('wallet_id', database.types.guid.GUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accounts')
    # ### end Alembic commands ###
